#:schema node_modules/wrangler/config-schema.json
name = "live-geojson-frontend"
compatibility_date = "2024-12-30"
pages_build_output_dir = './.output/public'

[env.production]
  NUXT_PUBLIC_SERVER = "live-geojson-server.laporisbraindead8080.workers.dev"
